# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='descripton',
            new_name='description',
        ),
    ]
