# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20160506_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='a book'),
        ),
    ]
